data:
    feature: data/dev/feature.csv
    label: data/dev/label.csv
    class_indice_file: data/metadata/class_label_indices.txt
    stratified: True
dataloader_args:
    batch_size: 64
    num_workers: 1

optimizer:
    type: AdamW
    args:
        lr: 0.001

epochs: 100 
model:
    type: Crnn
    args: {pool_method: mean } #max,mean,soft,linear_soft, autoexp

outputpath: experiments/mean/

